# Generated by Django 4.1.5 on 2023-01-16 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neme', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('dis', models.TextField()),
            ],
        ),
    ]
